Pip Note PipNote
===


## pip コマンド

```
pip search PACKAGE         パッケージの検索
pip list                   インストール済み
pip install PACKAGE        まあこれはいつもどおりてきとうに。
pip freeze > TXT_NAME      インストールしたパッケージ一覧をファイルに。
pip install -r TXT_NAME    ファイルからまとめてインストール。
pip uninstall -y PACKAGE   アンインストール。

pip list -o                更新があるパッケージを表示
pip install PACKAGE -U     パッケージを更新
```


## アップグレード

```
pip install --upgrade pip
```

これで ImportError が発生することがある。

```
ImportError: cannot import name 'main'
```


## そのプロジェクトで使われているモジュールだけを freeze

へー、こんなのあるんだ。

```
pip install pipreqs
pipreqs path/to/project
```


## ReadTimeoutError

エラー文はこれ。

```plaintext
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pipenv/
```

`--trusted-host` オプションをつけて install してみたら、しばらく変わらず ReadTimeoutError が出ていたのだけれど、そのまま眺めていたら install が始まって完了した。そしてその後は、普通に pip install できるようになった。謎。

```bash
$ pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org pipenv
```

これは Windows で発生した。同じ Wifi 下にある Mac では発生しなかった。
